#!/bin/bash

set -e

root_dir=$(dirname "$0")

env="$1"
if [ -z "$env" ]; then
    echo "Environment is required." >&2
    exit 1
fi
if [ "$env" != "development" ] && [ "$env" != "production" ]; then
    echo "Environment must be 'development' or 'production'." >&2
    exit 1
fi

public_dir="$2"
if [ -z "$public_dir" ]; then
    public_dir="${root_dir}/public"
fi

mkdir -p "$public_dir"
rm -rf "${public_dir:?}"/*

cp "${root_dir}/static"/* "$public_dir"

cp \
    "$(go env GOROOT)/lib/wasm/wasm_exec.js" \
    "${public_dir}/wasm_exec.js"

GOOS=js GOARCH=wasm go build \
    -o "${public_dir}/main.wasm" \
    "${root_dir}/cmd/client-hypp/main.go"
chmod -x "${public_dir}/main.wasm"

if [ "$env" = "production" ]; then
    mv "${public_dir}/main.wasm" "${public_dir}/main.wasm.tmp"
    wasm-opt "${public_dir}/main.wasm.tmp" -Oz --enable-bulk-memory -o "${public_dir}/main.wasm"
    rm "${public_dir}/main.wasm.tmp"
fi

go run "${root_dir}/cmd/static/main.go" "$public_dir"

GOOS=js GOARCH=wasm go build \
    -o "${root_dir}/cmd/fairytale/main.wasm" \
    "${root_dir}/cmd/fairytale/main.go"

sass "${root_dir}/scss:${public_dir}"

readarray -t files_to_compress < <(find "$public_dir" -type f ! -name '*.gz' ! -name '*.br')
gzip --best --force --keep "${files_to_compress[@]}"

# It takes a long time to compress main.wasm with brotli, so we only do it for production.
if [ "$env" = "production" ]; then
    brotli --best --force --keep "${files_to_compress[@]}"
fi
