#!/bin/bash

root_dir=$(dirname "$0")

env="$1"
if [ -z "$env" ]; then
    echo "Environment is required." >&2
    exit 1
fi
if [ "$env" != "development" ] && [ "$env" != "production" ]; then
    echo "Environment must be 'development' or 'production'." >&2
    exit 1
fi

public_dir="$2"
if [ -z "$public_dir" ]; then
    public_dir="${root_dir}/public"
fi

cp "${root_dir}/static"/* "$public_dir"

cp \
    "$(go env GOROOT)/misc/wasm/wasm_exec.js" \
    "${public_dir}/wasm_exec.js"

GOOS=js GOARCH=wasm go build \
    -o "${public_dir}/main.wasm" \
    "${root_dir}/cmd/client-hypp/main.go"

go run "${root_dir}/cmd/static/main.go" "$public_dir"

GOOS=js GOARCH=wasm go build \
    -o "${root_dir}/cmd/fairytale/main.wasm" \
    "${root_dir}/cmd/fairytale/main.go"

if [ "$env" = "production" ]; then
    sass "${root_dir}/scss:${public_dir}"
fi

readarray -t files_to_compress < <(find "$public_dir" -type f ! -name '*.gz' ! -name '*.br')
gzip --best --force --keep "${files_to_compress[@]}"
brotli --best --force --keep "${files_to_compress[@]}"
