// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package state

import (
	"errors"
	"fmt"
)

const (
	// SignalingStatusDefault is a SignalingStatus of type Default.
	SignalingStatusDefault SignalingStatus = iota
	// SignalingStatusWebSocketError is a SignalingStatus of type Web-Socket-Error.
	SignalingStatusWebSocketError
	// SignalingStatusIsConnectedToWebSocket is a SignalingStatus of type Is-Connected-To-Web-Socket.
	SignalingStatusIsConnectedToWebSocket
	// SignalingStatusOpponentIsConnectedToWebSocket is a SignalingStatus of type Opponent-Is-Connected-To-Web-Socket.
	SignalingStatusOpponentIsConnectedToWebSocket
	// SignalingStatusWebRtcError is a SignalingStatus of type Web-Rtc-Error.
	SignalingStatusWebRtcError
)

var ErrInvalidSignalingStatus = errors.New("not a valid SignalingStatus")

const _SignalingStatusName = "defaultweb-socket-erroris-connected-to-web-socketopponent-is-connected-to-web-socketweb-rtc-error"

var _SignalingStatusMap = map[SignalingStatus]string{
	SignalingStatusDefault:                        _SignalingStatusName[0:7],
	SignalingStatusWebSocketError:                 _SignalingStatusName[7:23],
	SignalingStatusIsConnectedToWebSocket:         _SignalingStatusName[23:49],
	SignalingStatusOpponentIsConnectedToWebSocket: _SignalingStatusName[49:84],
	SignalingStatusWebRtcError:                    _SignalingStatusName[84:97],
}

// String implements the Stringer interface.
func (x SignalingStatus) String() string {
	if str, ok := _SignalingStatusMap[x]; ok {
		return str
	}
	return fmt.Sprintf("SignalingStatus(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x SignalingStatus) IsValid() bool {
	_, ok := _SignalingStatusMap[x]
	return ok
}

var _SignalingStatusValue = map[string]SignalingStatus{
	_SignalingStatusName[0:7]:   SignalingStatusDefault,
	_SignalingStatusName[7:23]:  SignalingStatusWebSocketError,
	_SignalingStatusName[23:49]: SignalingStatusIsConnectedToWebSocket,
	_SignalingStatusName[49:84]: SignalingStatusOpponentIsConnectedToWebSocket,
	_SignalingStatusName[84:97]: SignalingStatusWebRtcError,
}

// ParseSignalingStatus attempts to convert a string to a SignalingStatus.
func ParseSignalingStatus(name string) (SignalingStatus, error) {
	if x, ok := _SignalingStatusValue[name]; ok {
		return x, nil
	}
	return SignalingStatus(0), fmt.Errorf("%s is %w", name, ErrInvalidSignalingStatus)
}

// MarshalText implements the text marshaller method.
func (x SignalingStatus) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *SignalingStatus) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseSignalingStatus(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
