name: Build

on:
  [push]
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: macabot/senet-builder:0.1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
          cache: true

      - name: Run build script
        run: ./build

      - name: Upload 'public' directory as artifact
        uses: actions/upload-artifact@v4
        with:
          name: public-artifact
          path: public
