name: Build

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: macabot/senet-builder:0.1.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
          cache: true

      - name: Run build script
        run: ./build production
